version: "3"
services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    volumes:
      - data:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sorcerous-sundries
    ports:
      - "5432:5432"
  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      POSTGRES_HOST: postgres_db
    depends_on:
      - postgres_db
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    depends_on:
      - server
volumes:
  data:
