###
GET http://localhost:5000/setup

###
GET http://localhost:5000

###

###
POST http://localhost:5000
Content-Type: application/json

{
    "name": "anastasiya1",
    "location": "some location1"
}
###