version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app-codename-faerun
  app:
    image: app-codename-faerun
    ports:
      - 5000:8080
