###
GET http://localhost:5000/tasks

###

GET http://localhost:5000/tasks/659c165d90642fd25ceb282f

###

POST http://localhost:5000/tasks
Content-Type: application/json

{
    "text": "Kill Netherbrain"
}

###

DELETE http://localhost:5000/tasks/659c17a914f3846232fe3828

###

PUT http://localhost:5000/tasks/659c21a487116be0c8ceda05/complete

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "email": "anastasiya.sychova@gmail.com",
    "password": "password"
}

###

POST http://localhost:5000/
Content-Type: application/json

{
    "email": "anastasiya.sychova@gmail.com",
    "password": "password"
}

###